# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ae37170302c3f49b04e86859c923e403ce917c230cc24338086da4262d15f957284ad9e3d55aaf96e8f6399fb8d7664670d1df28ad59357e57eca8f91b8f072

test:
  secret_key_base: 746b079a11fa311179765d560947fb25892054f35647562df86b18fc44753b335e90aa80e27c401a735942987691a351ced27e82d12b5437e7b62e2555f32ede

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
